### ISSUE TITLE
Change icon / setMarker

### ISSUE THREAD

**Issue by rafivian** [vipulasri/Timeline-View#11]
How to setMarker or change the icon

<com.vipul.hp_hp.timelineview.TimelineView
                android:id="@+id/red_marker"
                android:layout_width="wrap_content"
                android:layout_height="match_parent" 
                app:marker_size="35dp"
                app:marker="@drawable/ic_timeline_red"
                app:line_size="2dp"
                app:line="@android:color/black"/>

I use app:marker to change icon from xml

how to change the icon or marker from java code?

I got some error when I change it
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.content.Context.getDrawable(int)' on a null object reference

this is my java code

Drawable res = ContextCompat.getDrawable(context, R.drawable.ic_timeline_blue); 

        if(timeLineModel.getJenis().equalsIgnoreCase("1")){ 
            holder.mTimelineView.setMarker(res);
        }

can you help me please

thank you so much

**Comment by vipulasri** [comment]
@rafivian, You don't need to perform an extra step for this. Just use like this : 

`holder.mTimelineView.setMarker(context.getResources().getDrawable(R.drawable.ic_timeline_blue));`
OR 

`holder.mTimelineView.setMarker(R.drawable.ic_timeline_blue);`
