### ISSUE TITLE
line broke when set marker size

### ISSUE THREAD

**Issue by caotian** [vipulasri/Timeline-View#15]
line broke when set each marker size not the same size, any idea?

**Comment by vipulasri** [comment]
@caotian can you please post any screenshot of it.

**Comment by caotian** [comment]
![1](https://cloud.githubusercontent.com/assets/3139199/16574575/08b4d49a-42b3-11e6-9360-c4d7b532d603.jpg)

below is I have done in ios:
![2](https://cloud.githubusercontent.com/assets/3139199/16574599/4a0994da-42b3-11e6-995e-6973fdefd626.jpg)

**Comment by vipulasri** [comment]
I think according to my code or implementation of Timeline view this was supposed to happen. I will have to change the implementation of it, according to this case. Can you provide me the link to above iOS library of yours? One more thing can you tell me the implementation logic of your iOS Library?

**Comment by caotian** [comment]
I did it myself in ios, not using any library, just by customized tableview cells.

**Comment by jervan** [comment]
Looks like the iOS implementation adjusts the layout margins to keep the marker in the center of the view as well as the view the same size even with larger marker size.

**Comment by vipulasri** [comment]
@jervan  I have a workaround for you, you can simply apply the big drawable as marker and while you are applying smaller marker by calculating the smaller drawable `width - bigger drawable width` apply that much padding to smaller one. One more thing `linePadding` has introduced in `v1.0.5` so that you can apply similar line effect of ios on android

**Comment by raquezha** [comment]
there's a temporary solution where you can solve this by putting the timeline view inside linear layout with fixed widthand gravity to center and set your timelineview with to wrap content 

 ```
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:gravity="center"
        android:orientation="horizontal">
     <LinearLayout <!-- TIMELINVIEW -->
             android:layout_width="30dp" <!-- FIXED WIDTH -->
             android:layout_height="match_parent"
             android:layout_gravity="center" <!-- GRAVITY -->
             android:gravity="center"  <!-- GRAVITY -->
             android:orientation="vertical">

           <com.github.vipulasri.timelineview.TimelineView
                      android:id="@+id/timeline"
                      android:layout_width="wrap_content"
                      android:layout_height="match_parent"
                     android:layout_gravity="center"/>
     </LinearLayout>
     
     <!-- YOUR CONTENT HERE -->
</LinearLayout>
```
