### ISSUE TITLE
markerInCenter programmatically

### ISSUE THREAD

**Issue by jretorna** [vipulasri/Timeline-View#17]
Hello,

Is it possible to set marker in center programmatically please ?

**Comment by vipulasri** [comment]
@jretorna currently there is no way of doing it programmatically. I have intentionally not provided that option as the position of marker is determined during the declaration in XML. Changing its position dynamically will give an irregular TimeLine View which will result in bad UI.

Can you please explain me your use case?

**Comment by jretorna** [comment]
I just wanted to insert an unique timeline view in a header to show if the clicked point is the first, the last or a point in the middle. But I managed to do what I wanted using an other method, calling initLine with the  parameter BEGIN, NORMAL or END.
Thx
