### ISSUE TITLE
Change color of marker

### ISSUE THREAD

**Issue by jossiwolf** [vipulasri/Timeline-View#2]
Is this possible?

**Comment by vipulasri** [comment]
yes you can. For that you can have a drawable.
For eg.
 **new_marker.xml**

`<?xml version="1.0" encoding="utf-8"?>
<shape
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="@android:color/holo_green_dark"/> //change the color you want to display
</shape>`


And in main layout : 

`<com.vipul.hp_hp.timelineview.TimelineView
android:id="@+id/time_marker"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:paddingTop="30dp"
android:paddingBottom="30dp"
android:paddingLeft="10dp"
android:paddingRight="10dp"
app:marker="@drawable/new_marker"
app:marker_size="25dp"
app:line_size="2dp"
app:line="@color/colorPrimary"/>`
