### ISSUE TITLE
Timeline-View requires that my adapter can't have two or more item view types.

### ISSUE THREAD

**Issue by erehmi** [vipulasri/Timeline-View#20]
The sample source, as follows:
```
public class TimeLineAdapter extends RecyclerView.Adapter<TimeLineViewHolder> {
    ... ...
    @Override
    public int getItemViewType(int position) {
        return TimelineView.getTimeLineViewType(position,getItemCount());
    }
```
And check the `TimelineView.getTimeLineViewType(...)` function, as follows:
```
 public class TimelineView extends View {
     public static int getTimeLineViewType(int position, int total_size) {
         if(total_size == 1) {
             return LineType.ONLYONE;
         } else if(position == 0) {
             return LineType.BEGIN;
         } else if(position == total_size - 1) {
             return LineType.END;
         } else {
             return LineType.NORMAL;
         }
     }
``` 
As mentioned above, if use Timeline-View, then the adapter just have 4 item view types(They are : LineType.ONLYONE, LineType.BEGIN, LineType.END and LineType.NORMAL). 
**That is to say that Timeline-View assume that the developer defines only ONE type of item view. If defines two or more item view types, there is a conflict with the item view types defined by Timeline-View.**

Fix this issue, there is a solution: it is similar to `View.MeasureSpec`. 
**The higher 2-bits is used to define TimelineView types, and the lower 30-bits is used to define user's types.**

**Comment by erehmi** [comment]
If use the solution above, the max count of item view types is: 
**4 x N**

p.s. N is the count of item view types defined by the developer

**Comment by vipulasri** [comment]
@erehmi You can definitely use View Types other than 1 to 4.

**Comment by tprochazka** [comment]
I think that much better would be possible to update existing view to the different state.
I mean that instead of initLine() there will be setViewType() that will always update the rendering mode.
I don't need any benefit to create several different view types according view type. It sill call the onDraw() method when item is displayed, there is no caching.

**Comment by tprochazka** [comment]
I did it here
https://github.com/tprochazka/Timeline-View/commit/375ab03d8474849bea7c81d522380b2912a77890
