### ISSUE TITLE
Change Line Color Dynamically As Per Position

### ISSUE THREAD

**Issue by nahba** [vipulasri/Timeline-View#21]
Hi there,

Is there any way to change line color dynamically as per position? I mean to say that initially lines are drawn with gray color. Now as position gets changed based on button click, upto that position line's color changes to red. For example, I have 5 markers. All makers color are gray initially along with lines. Now I press button so my current position is 1. Now I want to change color of marker at 0 and 1 position and line between 0 and 1 to red.

Please refer below image.
![required](https://cloud.githubusercontent.com/assets/2108964/21759688/38d8cabc-d66c-11e6-94cb-3c92f233d3d6.png)

How can I achieve this?

**Comment by vipulasri** [comment]
@nahba Yes you can change the color of line using `setStartLine()` and `setEndLine()` methods.

**Comment by nahba** [comment]
@vipulasri Those methods takes `Drawable`. I have passed shape created using `xml` (as below) but did not work.

`<?xml version="1.0" encoding="utf-8"?>
<shape
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:shape="line">
	<solid android:color="@color/colorPrimaryDark"/>
	<stroke android:width="2dp"
		android:color="@color/colorPrimaryDark"/>
</shape>`

**Comment by vipulasri** [comment]
@nahba added in library v1.0.4

**Comment by balasaheb143** [comment]
setStartLine(color,Type ) and setEndLine(coor ,Type ) not work i pass color but color not change

**Comment by NimaaZx** [comment]
thanks developers. for those who get stucked for this feature. you should write code like this in your adapter. important part of this code is calling getItemViewType(). they prepared all things you need.

```
    private fun setEndStartMarket(holder: TimeLineViewHolder,position: Int)
    {
        holder.timeline.setStartLineColor(R.color.material_grey_500,getItemViewType(position))
    }
```
