### ISSUE TITLE
Hi,could you please add dotted effect for your awesome Timeline-View?

### ISSUE THREAD

**Issue by mccccccmike** [vipulasri/Timeline-View#22]

**Comment by sandeshlasnapure** [comment]
Any update on this?

**Comment by vipulasri** [comment]
@sandeshlasnapure not yet, still working on it.

**Comment by sandeshlasnapure** [comment]
ok thanks

**Comment by MakoFeng** [comment]
Any update on this?

**Comment by vipulasri** [comment]
@MakoFeng  not yet.

**Comment by YogeshLegendkiller** [comment]
first of all i must thank you for the fantastic lib ,  only dotted line is missing any updates on this?

**Comment by vipulasri** [comment]
This will take sometime as I will have to  re-write the logic

**Comment by vipulasri** [comment]
@mccccccmike @sandeshlasnapure @MakoFeng @YogeshLegendkiller 
New library version is available that supports this feature.
