### ISSUE TITLE
Issue displaying Large images on the timeline 

### ISSUE THREAD

**Issue by pavankr1** [vipulasri/Timeline-View#23]
Using Timeline-View to display images. Images that exceed 1mb don't seem to show up.

**Comment by vipulasri** [comment]
@pavankr1 I would suggest not to use images that much of size as it will require much more processing on the device each time it is drawn. GPU will have to do extra processing for each element while drawing. It is recommended to use vector drawable's(size around 1KB ~ 3KB) as android now support them, which will even reduce your app size as well as you don't have put each density dependent drawable's for each device.

**Comment by pavankr1** [comment]
Thanks for getting back. will try that.
