### ISSUE TITLE
ImageView instead of marker

### ISSUE THREAD

**Issue by liveneato** [vipulasri/Timeline-View#24]
Anyway to change the green marker to an ImageView?

**Comment by vipulasri** [comment]
@liveneato No, you cannot set drawable to `ImageView` but definitely you can change the green marker to any other drawable you want.

**Comment by liveneato** [comment]
I kind of came up with a solution to get the effect I wanted. Here it is below:

 <RelativeLayout
        android:layout_width="wrap_content"
        android:layout_height="match_parent">

        <com.github.vipulasri.timelineview.TimelineView
            android:id="@+id/timelineView"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_centerInParent="true"
            app:line="?colorAccent"
            app:markerSize="65dp" />

        <de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="65dp"
            android:layout_height="65dp"
            android:layout_centerInParent="true"
            app:civ_border_color="@color/colorAccent"
            app:civ_border_width="2dp" />
    </RelativeLayout>
