### ISSUE TITLE
how to remove line above the first item in the recyclerview and line below the last item in the recyclerview?

### ISSUE THREAD

**Issue by Frankenstein666** [vipulasri/Timeline-View#25]
how to remove line above the **first** item in the recyclerview and line below the **last** item in the recyclerview?

**Comment by vipulasri** [comment]
Please see README. 

Override getItemViewType() method in your recylerview adapter 

 @Override
    public int getItemViewType(int position) {
        return TimelineView.getTimeLineViewType(position,getItemCount());
    }

You can also see the sample app, link can be found in README
