### ISSUE TITLE
issue with vector drawable below sdk version less than 21

### ISSUE THREAD

**Issue by Frankenstein666** [vipulasri/Timeline-View#27]
I am getting a crash because of  following exception: 

_`android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/ic_marker_active.png from xml type xml resource ID #0x7f020071. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.`_

any idead what might be the issue?

**Comment by vipulasri** [comment]
See this example of making Vector Drawables compatible below lollipop, [TimeLineAdapter](https://github.com/vipulasri/Timeline-View/blob/master/app/src/main/java/com/github/vipulasri/timeline/TimeLineAdapter.java) and [VectorDrawableUtils](https://github.com/vipulasri/Timeline-View/blob/master/app/src/main/java/com/github/vipulasri/timeline/utils/VectorDrawableUtils.java) to support vector drawable's below lollipop
