### ISSUE TITLE
hiding the first half marker line on first TimeLineView.

### ISSUE THREAD

**Issue by Vic003** [vipulasri/Timeline-View#31]
Is there is any option to hide the first half marker line of the TimeLineView on very first so it look something like this.
O--------O--------O----
instead of
----O--------O--------O----

**Comment by vipulasri** [comment]
@Vic003 This cannot happen. Please share your code.

**Comment by Vic003** [comment]
@vipulasri in your TimeLineView are these codes are drawing the line

  if(mStartLine != null) {
                mStartLine.setBounds(0, pTop + (mBounds.height()/2), mBounds.left - mLinePadding, (mBounds.height()/2) + pTop + mLineSize);
            }

            if(mEndLine != null) {
                mEndLine.setBounds(mBounds.right + mLinePadding, pTop + (mBounds.height()/2), width, (mBounds.height()/2) + pTop + mLineSize);
            }

make a parameter to pass the position of RecyclerView here and modify it to draw second half line

**Comment by vipulasri** [comment]
@Vic003 you need to override `getItemViewType()` method in your recyclerview adapter. Its nothing to do with my `TimelineView` code.

```
@Override
    public int getItemViewType(int position) {
        return TimelineView.getTimeLineViewType(position,getItemCount());
    }
```

Please see [sample app code](https://github.com/vipulasri/Timeline-View/tree/master/app).

**Comment by vipulasri** [comment]
@Vic003 
To get this ----O--------O--------O---- output, don't override `getItemViewType()` method in your RecyclerView adapter.
