### ISSUE TITLE
Drawable Marker doesn't support SVG drawables

### ISSUE THREAD

**Issue by GitHubMurt** [vipulasri/Timeline-View#32]
It's common issue that in order to use SVG on pre-KitKat you have to use in ImageView
app:srcCompat instead of android:src.

The same situation here, but not handled. It throws exception.

**Comment by vipulasri** [comment]
@GitHubMurt You can definitely use SVG's in Drawable Marker. I have already added the code for that in the [sample app](https://github.com/vipulasri/Timeline-View/tree/master/app). Please look at below code in [TimeLineAdapter](https://github.com/vipulasri/Timeline-View/blob/master/app/src/main/java/com/github/vipulasri/timeline/TimeLineAdapter.java)

```
if(timeLineModel.getStatus() == OrderStatus.INACTIVE) {
            holder.mTimelineView.setMarker(VectorDrawableUtils.getDrawable(mContext, R.drawable.ic_marker_inactive, android.R.color.darker_gray));
        } else if(timeLineModel.getStatus() == OrderStatus.ACTIVE) {
            holder.mTimelineView.setMarker(VectorDrawableUtils.getDrawable(mContext, R.drawable.ic_marker_active, R.color.colorPrimary));
        } else {
            holder.mTimelineView.setMarker(ContextCompat.getDrawable(mContext, R.drawable.ic_marker), ContextCompat.getColor(mContext, R.color.colorPrimary));
}
```

Use `VectorDrawableCompat` to support Vector Drawables in pre-lollipop devices. You can also use [VectorDrawableUtils](https://github.com/vipulasri/Timeline-View/blob/master/app/src/main/java/com/github/vipulasri/timeline/utils/VectorDrawableUtils.java) file available in my sample code.

**Comment by GitHubMurt** [comment]
Ok, but let's try put your drawable directly inside XML, not In a RecyclerAdapter

**Comment by vipulasri** [comment]
Currently, It doesn't support vector drawables in XML directly. You can set vector drawables dynamically to Timeline View.

**Comment by GitHubMurt** [comment]
Ok Thanks, It may be helpful for other if you will put that information in the main page

**Comment by vipulasri** [comment]
Yeah sure. I will take it as note and add it asap. Actually, I didn't add support of vector drawables directly through xml as it will unnecessarily increase the size of library (just by addition of support-vector-drawable library).
