### ISSUE TITLE
Is there any way to clip the bottom most line without touching the end of screen ?

### ISSUE THREAD

**Issue by bharath-koteswarao** [vipulasri/Timeline-View#34]
<b>It is not good to see the line touching both the ends of screen. It would have been good if there is some way to clip the first and last lines</b>
<br/>
And by the way thanks a lot for making such a wonderful view. I'm using it in my app <strong>Wheelo</strong>

**Comment by vipulasri** [comment]
@bharath-koteswarao can you please show me the screenshot and code, as I am not able to get the issue you are facing.

**Comment by bharath-koteswarao** [comment]
It has been resolved. I had some margin to layout initially so I've faced this
