### ISSUE TITLE
Change marker color after a click

### ISSUE THREAD

**Issue by pedroseabra1091** [vipulasri/Timeline-View#36]
I am trying to change the marker color after an item click. However, it seems `setMarkerColor()` only works on the `onBindViewHolder()`. Is this true?

**Comment by vipulasri** [comment]
Yes, it will change its state on `onBindViewHolder` but you can still change the marker color by getting the particular view holder by using `getAdapterPosition()` and then make marker color changes to that view holder.

**Comment by pedroseabra1091** [comment]
Hey sorry to bother you again. But this not true. I am able to change background color within the view holder, however i cannot change the marker color. 

`
public static class HistoryViewHolder extends RecyclerView.ViewHolder {
...
@OnClick(R.id.item_history_wrapper)` void pressHistoryPoint() {
      historyLine.setMarkerColor(ContextCompat.getColor(root.context, R.color.colorAccent));
      root.pressHistoryPoint(getAdapterPosition(), this);
    }
  }`

**Comment by vipulasri** [comment]
@pedroseabra1091 You need to get the holder first and then apply the marker color. I would suggest maintaining a state variable in your custom object.
