### ISSUE TITLE
How to start the first timeline with a dot not line?

### ISSUE THREAD

**Issue by satyres** [vipulasri/Timeline-View#38]
Hi , first thank you for this nice library ,
I searched a lot but did not find how to start the first timeline with a dot not line?
please tell me how to do it like this
https://raw.githubusercontent.com/vipulasri/Timeline-View/master/art/showcase.png
Best regards

**Comment by vipulasri** [comment]
@satyres Please check out the[ sample code](https://github.com/vipulasri/Timeline-View/tree/master/app) and README. All things are already mentioned.

**Comment by satyres** [comment]
Thank you so much for your help !
got it now :)
