### ISSUE TITLE
Timeline-View delete items from recyclerview

### ISSUE THREAD

**Issue by 6AnkitaShetty** [vipulasri/Timeline-View#39]
Can someone explain how to remove items from recyclerview using this library?

Eg.
 if (TextUtils.isEmpty(timeLineModel.getDisplayName())) {
           //delete holder.itemView
        }

**Comment by vipulasri** [comment]
@6AnkitaShetty this is related to `RecyclerView` not `Timeline-View`.
P.S: use `list.remove(position)` then `notifyItemRemoved(position);` 
Checkout these SO Answers for better understanding https://stackoverflow.com/a/33211061/3140227
