### ISSUE TITLE
Line is broken 

### ISSUE THREAD

**Issue by GitHubMurt** [vipulasri/Timeline-View#41]
Hey lines those connect icons (markers) are not painted correctly.
<img width="43" alt="zrzut ekranu 2017-11-27 o 13 09 02" src="https://user-images.githubusercontent.com/12357195/33266313-62344240-d375-11e7-800d-b632fb02ee66.png">

After I scroll down, and then scroll up (recycle mechinism) line move to the correct place

Height of my element on the list is not constans ( sometimes more text in many lines)
Item of recycle View adapter looks like

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              xmlns:tools="http://schemas.android.com/tools"
              android:orientation="horizontal"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
    android:paddingLeft="8dp"
    android:paddingRight="8dp">

    <com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/timeline_marker"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        app:markerSize="36dp"
        app:lineSize="2dp"
        app:line="@color/teal"
        app:linePadding="0dp"
        app:markerInCenter="true"
        app:marker="@drawable/ic_service_history_tire"
        android:layout_marginLeft="8dp"
        android:layout_gravity="center_vertical"/>

<OtherView....>
</LinearLayout>
```

**Comment by vipulasri** [comment]
Hey, can you please share some your code. So that I can look into the
problem.

**Comment by romitarora** [comment]
I am also getting same issue of @GitHubMurt ... in nexus 4(5.1.1) its working but in samsung mini 4 (4.4.2) not working. when i scroll recyclerview and come back its working.

**Comment by romitarora** [comment]
Sorry @vipulasri , this is my mistake, only notifyItemChanged() is not working in my case so i changed it to  **notifyItemChanged(i)** and its working now.
