### ISSUE TITLE
the line does not show 

### ISSUE THREAD

**Issue by 1253062595** [vipulasri/Timeline-View#42]
the line does not show up when i use your view by gradle, my code is below, can you help me find the problem?
-----------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    
    <com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/tlv_a_timeline"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_marginTop="@dimen/dimen_10"
        app:markerSize="20dp"
        app:lineSize="3dp"
        app:line="@color/black"
        app:linePadding="5dp"
        />

    
    <RelativeLayout
        android:id="@+id/ll_adapter_rv_a_timeline_right"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="@dimen/dimen_5"
        android:layout_marginLeft="@dimen/dimen_10"
        android:layout_marginRight="@dimen/dimen_10"
        android:layout_marginTop="@dimen/dimen_5"
        android:layout_toRightOf="@id/tlv_a_timeline"
        android:background="@drawable/shape_c_rect_3_bg_white">

        
        <TextView
            android:id="@+id/tv_adapter_rv_a_timeline_date"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="@dimen/dimen_5"
            android:layout_marginRight="@dimen/dimen_5"
            android:ellipsize="end"
            android:gravity="left|center_vertical"
            android:maxEms="20"
            android:singleLine="true"
            android:text="2017-12-11 12:50:23"
            android:textColor="@color/black"
            android:textSize="@dimen/font_12" />

        <View
            android:id="@+id/view_adapter_rv_a_timeline_1"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dimen_1"
            android:layout_below="@id/tv_adapter_rv_a_timeline_date"
            android:layout_centerInParent="true"
            android:background="@color/bg_line_lightgray" />

        
        <TextView
            android:id="@+id/tv_adapter_rv_a_timeline_title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/view_adapter_rv_a_timeline_1"
            android:layout_marginLeft="@dimen/dimen_5"
            android:layout_marginRight="@dimen/dimen_5"
            android:ellipsize="end"
            android:gravity="left|center_vertical"
            android:maxEms="20"
            android:singleLine="true"
            android:text="timeline标题"
            android:textColor="@color/black"
            android:textSize="@dimen/font_16" />

        <View
            android:id="@+id/view_adapter_rv_a_timeline_2"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dimen_1"
            android:layout_below="@id/tv_adapter_rv_a_timeline_title"
            android:background="@color/bg_line_lightgray" />

        
        <TextView
            android:id="@+id/tv_adapter_rv_a_timeline_detail"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/view_adapter_rv_a_timeline_2"
            android:layout_marginLeft="@dimen/dimen_5"
            android:layout_marginRight="@dimen/dimen_5"
            android:ellipsize="end"
            android:gravity="left|center_vertical"
            android:maxEms="20"
            android:singleLine="true"
            android:text="timeline详情"
            android:textColor="@color/black"
            android:textSize="@dimen/font_12" />

    </RelativeLayout>

</RelativeLayout>

-----------------------------------------------------------------------------

public class MyViewHolder extends RecyclerView.ViewHolder {

        private TimelineView tlv;
        private TextView tvTitle;
        private TextView tvDetail;
        private TextView tvDate;

        public MyViewHolder(View view, int viewType) {
            super(view);
            tlv = view.findViewById(R.id.tlv_a_timeline);
            tlv.initLine(viewType);
            tvTitle = view.findViewById(R.id.tv_adapter_rv_a_timeline_title);
            tvDetail = view.findViewById(R.id.tv_adapter_rv_a_timeline_detail);
            tvDate = view.findViewById(R.id.tv_adapter_rv_a_timeline_date);
        }
    }

-----------------------------------------------------------------------------

![default](https://user-images.githubusercontent.com/13758734/33862017-a3e065e6-df1b-11e7-968d-1d23d844f96d.png)

**Comment by vipulasri** [comment]
@1253062595 Please show the whole code for `RecyclerView Adapter`

**Comment by 1253062595** [comment]
I 've solved the problem.
I change the root layout from RelativeLayout to LinearLayout, then it shows the line.
------------------------------------------------------------------------------
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="@dimen/dimen_16"
    android:orientation="horizontal">

    
    <com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/tlv_a_timeline"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_marginTop="@dimen/dimen_10"
        app:markerSize="20dp"
        app:lineSize="3dp"
        app:line="@color/black"
        app:linePadding="5dp"
        app:markerInCenter="false"
        />

    
    <RelativeLayout
        android:id="@+id/ll_adapter_rv_a_timeline_right"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="@dimen/dimen_5"
        android:layout_marginLeft="@dimen/dimen_10"
        android:layout_marginRight="@dimen/dimen_10"
        android:layout_marginTop="@dimen/dimen_5"
        android:background="@drawable/shape_c_rect_3_bg_white">

        
        <TextView
            android:id="@+id/tv_adapter_rv_a_timeline_date"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="@dimen/dimen_5"
            android:layout_marginRight="@dimen/dimen_5"
            android:ellipsize="end"
            android:gravity="left|center_vertical"
            android:maxEms="20"
            android:singleLine="true"
            android:text="2017-12-11 12:50:23"
            android:textColor="@color/black"
            android:textSize="@dimen/font_12" />

        <View
            android:id="@+id/view_adapter_rv_a_timeline_1"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dimen_1"
            android:layout_below="@id/tv_adapter_rv_a_timeline_date"
            android:layout_centerInParent="true"
            android:background="@color/bg_line_lightgray" />

        
        <TextView
            android:id="@+id/tv_adapter_rv_a_timeline_title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/view_adapter_rv_a_timeline_1"
            android:layout_marginLeft="@dimen/dimen_5"
            android:layout_marginRight="@dimen/dimen_5"
            android:ellipsize="end"
            android:gravity="left|center_vertical"
            android:maxEms="20"
            android:singleLine="true"
            android:text="timeline标题"
            android:textColor="@color/black"
            android:textSize="@dimen/font_16" />

        <View
            android:id="@+id/view_adapter_rv_a_timeline_2"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dimen_1"
            android:layout_below="@id/tv_adapter_rv_a_timeline_title"
            android:background="@color/bg_line_lightgray" />

        
        <TextView
            android:id="@+id/tv_adapter_rv_a_timeline_detail"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/view_adapter_rv_a_timeline_2"
            android:layout_marginLeft="@dimen/dimen_5"
            android:layout_marginRight="@dimen/dimen_5"
            android:ellipsize="end"
            android:gravity="left|center_vertical"
            android:maxEms="20"
            android:singleLine="true"
            android:text="timeline详情"
            android:textColor="@color/black"
            android:textSize="@dimen/font_12" />

    </RelativeLayout>

</LinearLayout>
------------------------------------------------------------------------------
![default](https://user-images.githubusercontent.com/13758734/33869675-10c6f3fe-df45-11e7-8568-6bd1eda84cd1.png)

**Comment by pattaniinfoway** [comment]
For me the line is not showing
