### ISSUE TITLE
How to reduce line height for first and last elements?

### ISSUE THREAD

**Issue by gowsikbrigita** [vipulasri/Timeline-View#45]

**Comment by vipulasri** [comment]
@gowsikbrigita currently, there's no way to reduce line height for the first and last element. But yes you can remove the top line from the first element and end line from the last element.

**Comment by gowsikbrigita** [comment]
Hi in the screenshot  the the upper half of  the first element is not visible how can i achieve this
![untitled](https://user-images.githubusercontent.com/18347093/35614694-f5980be0-0695-11e8-8962-42846804d869.jpg)

**Comment by gowsikbrigita** [comment]
@vipulasri  hey Sorry .... I forgot to call    initLine(viewType);  My bad....
Thanks for the reply....
