### ISSUE TITLE
Extra line in First and last items

### ISSUE THREAD

**Issue by pfieffer** [vipulasri/Timeline-View#46]
Hey, I have gone over the sample app provided and the methods available. But I cannot seem to remove the extra line spacing. I mean I have an Adapter, an item view and a recycler view, where I am loading the item views with the help of adapter. 
How can I disable that extra line on the first and last items.
I maybe missing something simple and I am sorry that I am posting this as an issues but I could not find resources on other places.

**Comment by vipulasri** [comment]
@pfieffer You must have skipped this line: https://github.com/vipulasri/Timeline-View/blob/588cb23f599142b8958e30f9329c17094a428247/app/src/main/java/com/github/vipulasri/timelineview/sample/TimeLineAdapter.java#L39

**Comment by pfieffer** [comment]
@vipulasri Thank you very much. I had a doubt that this was the problem back then, but I got caught up in implementing other stuffs and missed this. Thank you very much.
