### ISSUE TITLE
Why app crashes when use this library on 4.4.2 android version?

### ISSUE THREAD

**Issue by ahmed0123** [vipulasri/Timeline-View#54]

**Comment by vipulasri** [comment]
@ahmed0123 Please provide more information on this issue. Because I tried the app on 4.4.2 and it worked perfectly.

**Comment by pacosta** [comment]
This error,

If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.

when calling setMarker() with a vector drawable.

**Comment by vipulasri** [comment]
The library doesn't support `VectorDrawables` as supporting it will unnecessarily increase the library size. You need to use `VectorDrawableCompat` and then set the resulting drawable to `setMarker()` method.
