### ISSUE TITLE
Different View types!.

### ISSUE THREAD

**Issue by Devspm** [vipulasri/Timeline-View#56]
Hello there, 
Thanks for the nice library, How can I create multiple view types ?

**Comment by vipulasri** [comment]
@Devspm You can different types of view as you would do normally but just exclude the certain view types (see : [LineType)](https://github.com/vipulasri/Timeline-View/blob/master/timelineview/src/main/java/com/github/vipulasri/timelineview/LineType.java) while declaring/giving your views

**Comment by Devspm** [comment]
I overrode getItemViewType with my view type as you said and it works but ,I can't disable the lines at starting and ending poistion.See the image below.
![screenshot_1536219621](https://user-images.githubusercontent.com/34958091/45142651-aab66d00-b1d6-11e8-8501-2faf63eab433.png)

**Comment by Devspm** [comment]
you mean here,

`@Override
    public int getItemViewType(int position) {
        switch (timeLines.get(position).getType()) {
            case 20:
                return SIDE_BIT;
            default:
                return MAIN_ITEM;
        }
    }
`


won't using `TimelineView.getTimeLineViewType(position,getItemCount());`  be ignored here?

**Comment by Devspm** [comment]
So, if i'm having multiple view types ,i cannot use `getTimeLineViewType`..

**Comment by vipulasri** [comment]
You can use that in your else condition of your "getItemViewType()" method. As it will fallback to this automatically. 
To properly show the timeline view you need to implement this anyhow.
