### ISSUE TITLE
two or more activities for the same date

### ISSUE THREAD

**Issue by hardikvasa** [vipulasri/Timeline-View#57]
Awesome project Vipul.

I have a use case where I want to show two or more activities for the same date/day and hence I do not want the marker to be shown but instead just a straight blue line in the timeline. Is this possible? If not, can you share a drawable XML for the same?

**Comment by vipulasri** [comment]
I don't think there any solution for this kind of view but there's a workaround for this solution is setting the background colored marker drawable and setting it dynamically using 
```
setMarker()
``` 
method.

**Comment by hardikvasa** [comment]
Thanks for your quick response. Thats nice! One other way I was thinking is to bring down the marker size to some negligible size (for e.g. 3dp) so the timeline appears as a straight line.

If this feature is not going to be considered for this project, you can close this issue. Thnx.

**Comment by vipulasri** [comment]
Yeah, you can manipulate the market size as well to achieve this.
