### ISSUE TITLE
small bug in TimelineView.getTimelineViewType?

### ISSUE THREAD

**Issue by irascible** [vipulasri/Timeline-View#6]
I think the only-one check should happen first, otherwise you get a dangling line.

public static int getTimeLineViewType(int position, int total_size) {
        if(total_size == 1) {
            return LineType.ONLYONE;
        } else if(position == 0) {
            return LineType.BEGIN;
        } else if(position == total_size - 1) {
            return LineType.END;
        } else {
            return LineType.NORMAL;
        }
    }

**Comment by vipulasri** [comment]
can you provide some screenshot for the same, where it is not providing output as expected.

**Comment by vipulasri** [comment]
@irascible can you provide some screenshot for the same, where it is not providing output as expected.

**Comment by irascible** [comment]
![dangling_line](https://cloud.githubusercontent.com/assets/1003540/13594221/db5998fe-e502-11e5-8174-d59a1278cf0f.png)

**Comment by vipulasri** [comment]
@irascible , I think this is because you might be using a drawable with extra paddings.

**Comment by irascible** [comment]
I am not sure that applies. The picture in the comment above uses the original getTimeLineViewType() code. When I override it, as in the code snippet above, the picture becomes as follow. Note the absence of the dangling line.

![dangling_line_2](https://cloud.githubusercontent.com/assets/1003540/13594488/1e6af532-e505-11e5-8aa3-3b68fcc93336.png)

**Comment by vipulasri** [comment]
@irascible I am not able to get you. You want to display only one-item?

**Comment by irascible** [comment]
The model is dynamic. When it first starts, there is one item. Later there are more. The lines work fine when there is more than one item. I am merely fixing the case when there is only one. In the original code, it first checks that the item is at position zero and returns BEGIN. However, if there is only one item, it should return ONLYONE.Thus the fix above.

**Comment by vipulasri** [comment]
@irascible Okay sure, now i understood. I will soon release the new updated library.

**Comment by vidia** [comment]
I also had this issue.

**Comment by vipulasri** [comment]
Thank you @vidia . New Library version is updated with a fix to this.
