### ISSUE TITLE
setLineWidth and setStartLineColor and setEndLineColor not work.

### ISSUE THREAD

**Issue by milad7111** [vipulasri/Timeline-View#62]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2XL]
 - OS: [e.g. Android 9.0]
 - Version [e.g. 28]

**Comment by vipulasri** [comment]
@milad7111 which version are you using?

**Comment by milad7111** [comment]
Hi, Thanks, i am using V 1.1.0. i have an adapter that based on row TYPE, i want to change lineWidth but not work and there is no compile error or runtime error.  I changed lineColor eventually but lineWidth not worked. of course when i change LineWidth in xml, it worked.

Device: Galexy J7
OS : Android 7.0
