### ISSUE TITLE
Dashed error drawing

### ISSUE THREAD

**Issue by tcqq** [vipulasri/Timeline-View#63]
@vipulasri Now dashed is drawing error on Timeline-View, can you fix this? Thank you.
![image](https://user-images.githubusercontent.com/10644057/52261903-c8465900-2965-11e9-8248-5fec6d715a0a.png)
![image](https://user-images.githubusercontent.com/10644057/52261876-b369c580-2965-11e9-84af-9294d1c43bfa.png)

**Comment by vipulasri** [comment]
This is fixed in library v1.1.2
