### ISSUE TITLE
Request to add markerPaddingTop and markerPaddingBottom attributes

### ISSUE THREAD

**Issue by tcqq** [vipulasri/Timeline-View#66]
Request to add markerPaddingTop and markerPaddingBottom attributes. In order to fine tune the marker position in the high item.
![tim 20190213153448](https://user-images.githubusercontent.com/10644057/52694521-edaa1700-2fa4-11e9-8de1-18689745db23.jpg)

**Comment by mwshubham** [comment]
Looks a good solution.

**Comment by vipulasri** [comment]
Released v1.1.1
