### ISSUE TITLE
Update marker live if status changed 

### ISSUE THREAD

**Issue by Mozartuss** [vipulasri/Timeline-View#68]
**Please excuse my poor English**

I have different events and the events have a duration. Is the Event active I want to set the active_marker and if the event is finished the inactive_marker. The marker changes work great, but i have to restart the Fargment to see the changes. Or turn my Phone to landscape mode to refresh the RecyclerView  :laughing: . 
Is there a solution to update the marker dynamically like this in the RecyclingView? 

![timeline](https://i.stack.imgur.com/QoFVU.gif) 

***Now I change the Marker with this code in the TimelineAdapter***

```java
@Override
public void onBindViewHolder(@NonNull TimeLineViewHolder holder, int position) {
    TimeLineData timeLineData = feedList.get(position);

    Calendar currentDate = Calendar.getInstance();

    Calendar endDate = (Calendar) timeLineData.getRealTime().clone();
    endDate.add(Calendar.MINUTE, 5);   // Event Duration 

    if (currentDate.after(endDate)) {
        holder.timelineView.setMarker(holder.itemView.getContext().getDrawable(R.drawable.ic_marker_inactive));
    }
    if (currentDate.after(timeLineData.getRealTime()) && currentDate.before(endDate)) {
        holder.timelineView.setMarker(holder.itemView.getContext().getDrawable(R.drawable.ic_marker_active));
    }
    if (currentDate.before(timeLineData.getRealTime())) {
        holder.timelineView.setMarker(holder.itemView.getContext().getDrawable(R.drawable.ic_marker_future));
    }

    holder.title.setText(timeLineData.getStartup1() + " VS " + timeLineData.getStartup2());
    holder.time.setText(timeLineData.getTime()); 
}
```

**Comment by vipulasri** [comment]
There's nothing to do with the library. RecyclerView has a property to update a particular `ViewHolder` against a certain position using `notifyDataSetChanged()`
