### ISSUE TITLE
TImeline Attr Bottom sheet icon issue

### ISSUE THREAD

**Issue by mwshubham** [vipulasri/Timeline-View#70]
**Describe the bug**
Timeline attributes icon must be animated on the scroll. And it must point to downward whenever the bottom sheet is fully expanded.

**To Reproduce**
Click Options button on Main screen

**Expected behavior**
The arrow should point downward whenever the bottom sheet is fully expanded. And should dismiss the dialog when clicked

**Comment by vipulasri** [comment]
@mwshubham thanks for the input will look into this.
