### ISSUE TITLE
Not seeing the line between markers

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [vipulasri/Timeline-View#75]
I'm not seeing the line between the markers. I'm only seeing the markers

This is the code i'm using in my recycler item layout
 <com.github.vipulasri.timelineview.TimelineView
            android:id="@+id/timeline"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:endLineColor="@color/red_500"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:lineOrientation="vertical"
            app:linePadding="5dp"
            app:lineStyle="normal"
            app:lineWidth="10dp"
            app:marker="@color/red_500"
            app:markerInCenter="true"
            app:markerSize="10dp"
            app:startLineColor="@color/red_500" />

It would have been helpful if you had shown how to integrate this component in the recycler item layout xml

**Comment by vipulasri** [comment]
@kpradeepkumarreddy Can you show me some code supporting this.

**Comment by bastolaxantos** [comment]
I just implemented this library and line is not showing between marker.

**Comment by vipulasri** [comment]
@bastolaxantos Please show me some code so that I can help or point out where you are going wrong.

**Comment by bastolaxantos** [comment]
This is adapter class:
`public class MessageListAdapter extends RecyclerView.Adapter<MessageListAdapter.ViewHolder> {

    private List<Message> messageItemList;
    private ItemClickListener clickListener;

    public MessageListAdapter(List<Message> messageItemList, ItemClickListener clickListener) {
        this.messageItemList = messageItemList;
        this.clickListener = clickListener;
    }

    @Override
    public int getItemViewType(int position) {
        return TimelineView.getTimeLineViewType(position, getItemCount());
    }

    @NonNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        return new ViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.item_sms_group, parent, false), viewType);
    }

    @Override
    public void onBindViewHolder(@NonNull ViewHolder holder, int position) {

    }

    @Override
    public int getItemCount() {
        return messageItemList.size();
    }

    class ViewHolder extends RecyclerView.ViewHolder {

        TimelineView timelineView;

        ViewHolder(@NonNull View itemView, int viewType) {
            super(itemView);
            timelineView = itemView.findViewById(R.id.timeline);
            timelineView.initLine(viewType);
        }
    }

    public interface ItemClickListener {
        void onItemClicked(int position);
    }

}`

Item xml:

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal">

    <com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/timeline"
        android:layout_width="50dp"
        android:layout_height="wrap_content"
        app:lineWidth="10dp"
        app:markerSize="40dp"
        app:marker="@drawable/ic_sms"
        app:linePadding="5dp" />

    <androidx.cardview.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="4dp"
        app:contentPadding="8dp">

............ rest of view............

    </androidx.cardview.widget.CardView>
`

**Comment by vipulasri** [comment]
@bastolaxantos Adapter looks fine to me! can you show me your whole XML code? Or you can try using the library first in a separate sample app implementation.

**Comment by bastolaxantos** [comment]
> @bastolaxantos Adapter looks fine to me! can you show me your whole XML code? Or you can try using the library first in a separate sample app implementation.

here is item_sms_group.xml

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal">

    <com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/timeline"
        android:layout_width="50dp"
        android:layout_height="wrap_content"
        app:lineWidth="10dp"
        app:markerSize="40dp"
        app:marker="@drawable/ic_sms"
        app:linePadding="5dp" />

    <androidx.cardview.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="4dp"
        app:contentPadding="8dp">

            <LinearLayout
                android:id="@+id/sms_preview_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="10dp"
                android:layout_weight="1"
                android:orientation="vertical">

                <TextView
                    android:id="@+id/tv_date"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:ellipsize="end"
                    android:maxLines="1"
                    android:text="08:00 AM 17 April 2019" />


                <TextView
                    android:id="@+id/tv_title"
                    style="@style/TextAppearance.Compat.Notification.Title"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:ellipsize="end"
                    android:maxLines="1"
                    android:paddingTop="4dp"
                    android:paddingBottom="4dp"
                    android:text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ultricies nulla enim, at pulvinar augue mattis id." />

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal">

                    <ImageView
                        android:layout_width="20dp"
                        android:layout_height="20dp"
                        android:src="@drawable/ic_peoples" />

                    <TextView
                        android:id="@+id/tv_phone_count"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="8dp"
                        android:text="24 phones" />

                </LinearLayout>

            </LinearLayout>

    </androidx.cardview.widget.CardView>
</LinearLayout>`

I will try running sample project later

**Comment by vipulasri** [comment]
@bastolaxantos You forgot to tell the `TimelineView` to match the height of the view.  Just replace `TimelineView` height from `wrap_content` to `match_parent`.

```
<com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/timeline"
        android:layout_width="50dp"
        android:layout_height="wrap_content"
        app:lineWidth="10dp"
        app:markerSize="40dp"
        app:marker="@drawable/ic_sms"
        app:linePadding="5dp" />
```

**Comment by ZoneTYJ** [comment]
I find default mDrawEndLine=false,mDrawStartLine=false.
can you support attr  with DrawEndLine, DrawStartLine,and method initLine(int viewType) ?
