### ISSUE TITLE
can i use thise code in java

### ISSUE THREAD

**Issue by Avinash4201** [vipulasri/Timeline-View#77]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2XL]
 - OS: [e.g. Android 9.0]
 - Version [e.g. 28]

**Comment by Avinash4201** [comment]
I want java source code for your library

**Comment by vipulasri** [comment]
@Avinash4201 Java source code is not possible as moving forward everyone is opting for Kotlin.
