### ISSUE TITLE
Have setAdapter for TimelineView

### ISSUE THREAD

**Issue by chitgoks** [vipulasri/Timeline-View#79]
currently, it seems adapter is dependent on having it set in a recycleview

why not have the adapter be set directly to the timelineview?

**Comment by vipulasri** [comment]
@chitgoks You need to set the adapter to recycler view. Which is a must! 
Please refer to the official documentation: https://developer.android.com/guide/topics/ui/layout/recyclerview

**Comment by chitgoks** [comment]
hi vipulasri. thank you. im familiar with that. what i do not understand is in your sample code, and documentation the XML is <com.github.vipulasri.timelineview.TimelineView/>

So TimelineView is not to be used anymore but RecyclerView?

**Comment by vipulasri** [comment]
@chitgoks Yes, TimelineView is used in the item of RecyclerView
