### ISSUE TITLE
Make time line time sensitive

### ISSUE THREAD

**Issue by kaushalyap** [vipulasri/Timeline-View#83]
**Is your feature request related to a problem? Please describe.**
Currently Timeline-View is custom view with recyclerview it's not time sensitive. (gaps between items are same)

**Describe the solution you'd like**
Make Timeline-View time sensitive, so that the item gaps are proportional to the when the even occurred. If time gap is relatively large use a zig-zag to denote that.

Take a look at this [app](https://play.google.com/store/apps/details?id=com.twodimensions.timeline&hl=en) to understand what I mean by time sensitive.

**Comment by vipulasri** [comment]
@kaushalyap The scenario you are saying is not general, the library is made keeping in mind that it can be used for any general-purpose tracking irrespective of any specific scenario( in your case: time).
P.S: Don't misunderstand the name of the library with actual relationship with time.
