### ISSUE TITLE
Dynamic Progress Line

### ISSUE THREAD

**Issue by alvin96** [vipulasri/Timeline-View#85]
As the example shown below, the length of line is actually filled according to the given number which is a quite useful feature. Can this library achieve something similar like this?
![ss](https://user-images.githubusercontent.com/20142859/68824052-93271e00-06d0-11ea-97d2-d4070d7f2980.jpg)

**Comment by vipulasri** [comment]
@alvin96 this library can achieve this but you will have to write the logic on your side to support this behavior using 'setStartLine()' and 'setEndLine()' methods.

**Comment by alvin96** [comment]
> @alvin96 this library can achieve this but you will have to write the logic on your side to support this behavior using 'setStartLine()' and 'setEndLine()' methods.

Thanks 👍
