### ISSUE TITLE
Not seeing the line between markers in AndroidX

### ISSUE THREAD

**Issue by naveen-nuveda** [vipulasri/Timeline-View#86]
**Describe the bug**
Not seeing the line between markers after I converted my project to androidx. 

**To Reproduce**
Create a sample project in non-androidx , line is visible and now convert project to androidx and now line is not visible

**Expected behavior**
When the library is converting to androidx?. It should support androidx 

**Screenshots**
[https://ibb.co/0Djr6Dr](url)

**Smartphone (please complete the following information):**
-All

**Comment by vipulasri** [comment]
@naveen-nuveda, for now, you can use
`
android.useAndroidX=true
android.enableJetifier=true
`

**Comment by naveen-nuveda** [comment]
Sorry I missed initLine part which was working on before without inline. 
Now I added this showing line between markers

**Comment by fllaryora** [comment]
Please, reopen this.
From my point of view, I can see the reason to call this method.

**Comment by vipulasri** [comment]
@naveen-nuveda can you re-attach the image or screenshot and explain the issue

**Comment by naveen-nuveda** [comment]
@vipulasri sorry I can't able to produce screeenshot as of now. 
**Francisco Llaryora** suggested to reopen this issue. 
for my analysis older versions no need to call **initLine** method. this change breaks entire flow who just updated version in gradle and they didn't change any thing. 
Why can't we make **initLine** should automate

**Comment by vipulasri** [comment]
@naveen-nuveda `initLine` method has been there from start, though I get your concern as its custom view not a custom recycler view adapter. So, I don't think I can do much about it.

**Comment by naveen-nuveda** [comment]
Okay Thanks.  I am closing this issue
