### ISSUE TITLE
Problem in dynamic rows

### ISSUE THREAD

**Issue by novanto** [vipulasri/Timeline-View#9]
I used your library to a dynamic list - a list where the content can be with/without image. But there is some problem on row with images, you can see the problem below:

![timelineview-dynamiclist](https://cloud.githubusercontent.com/assets/3339477/14205624/d38c7dfc-f836-11e5-9989-f626a01dae95.png)

I have applied `match parent` on timeline view and it doesn't help me at all.

For the dynamic view, I used `View.VISIBLE` to show and `View.GONE` on the onBindViewHolder method.

I don't know whether this is a bug on the library or is it just me wrong in implementing it.

Your help will be really appreciated.

**Comment by vipulasri** [comment]
@novanto Please post xml code you have implemented.

**Comment by novanto** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="20dp"
        android:id="@+id/timeline_date"
        android:textAppearance="@style/TextAppearance.Medium"
        android:textColor="@color/colorAccent"
        android:layout_marginTop="30dp" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/timeline_time"
        android:layout_below="@+id/timeline_date"
        android:layout_marginTop="5dp"
        android:layout_marginLeft="20dp"
        android:textAppearance="@style/TextAppearance.Light"
        android:textSize="13sp"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textAppearance="@style/TextAppearance.Medium"
        android:layout_toRightOf="@+id/time_marker"
        android:textColor="@color/black"
        android:layout_marginTop="30dp"
        android:id="@+id/timeline_status"
        android:layout_marginLeft="10dp"/>

    <ImageView
        android:id="@+id/timeline_location_icon"
        android:layout_width="14dp"
        android:layout_height="14dp"
        android:layout_marginLeft="5dp"
        android:layout_marginTop="6dp"
        android:src="@drawable/ic_location_small"
        android:layout_below="@+id/timeline_status"
        android:layout_toRightOf="@+id/time_marker"
        android:tint="@color/text_dark_gray"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="2dp"
        android:layout_marginTop="5dp"
        android:layout_below="@+id/timeline_status"
        android:layout_toRightOf="@+id/timeline_location_icon"
        android:id="@+id/timeline_location"
        android:textColor="@color/text_dark_gray"
        android:layout_marginRight="15dp"/>

    <RelativeLayout
        android:id="@+id/timeline_image_container"
        android:layout_marginTop="10dp"
        android:layout_width="225dp"
        android:layout_height="225dp"
        android:layout_marginRight="15dp"
        android:layout_below="@id/timeline_location"
        android:layout_toRightOf="@id/time_marker"
        android:background="@drawable/bamboo">
        <de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/timeline_user_image"
            android:layout_width="35dp"
            android:layout_height="35dp"
            android:layout_alignParentBottom="true"
            android:layout_marginLeft="16dp"
            android:layout_marginBottom="16dp"
            android:src="@android:drawable/sym_def_app_icon"/>
        <TextView
            android:id="@+id/timeline_image_namelabel"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_toRightOf="@+id/timeline_user_image"
            android:layout_alignTop="@id/timeline_user_image"
            android:layout_marginLeft="12dp"
            android:textAllCaps="true"
            android:textSize="12sp"
            android:textAppearance="@style/TextAppearance.Medium"
            android:textColor="@android:color/white" />

        <TextView
            android:id="@+id/timeline_image_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@+id/timeline_image_namelabel"
            android:layout_marginTop="5dp"
            android:layout_marginLeft="12dp"
            android:layout_toRightOf="@+id/timeline_user_image"
            android:textColor="@android:color/white" />
        <ImageView
            android:id="@+id/timeline_image_view"
            android:layout_width="20dp"
            android:layout_height="20dp"
            android:src="@drawable/ic_search"
            android:layout_alignParentRight="true"
            android:layout_alignParentEnd="true"
            android:layout_marginTop="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"/>
    </RelativeLayout>

    <com.vipul.hp_hp.timelineview.TimelineView
        android:id="@+id/time_marker"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:paddingTop="30dp"
        android:paddingBottom="30dp"
        android:paddingLeft="15dp"
        android:paddingRight="15dp"
        android:layout_marginLeft="70dp"
        app:marker_size="15dp"
        app:line_size="2dp"
        app:marker="@drawable/timeline_marker_outline"
        app:line="@color/yellowBright"/>

</RelativeLayout>`

Here is the xml of the row item

**Comment by novanto** [comment]
I have fixed it, but I have to re-declare the row height on the adapter. Still I don't think the issue should be closed because the library should accommodate the dynamic rows like the IOS library here [https://github.com/edekhayser/Timeline](https://github.com/edekhayser/Timeline)

**Comment by ahmedoid** [comment]
@novanto  can you past your solution here because  here same issue
thank you

**Comment by novanto** [comment]
First you have to make sure the image's size is static. You can do this by declaring manually on xml layout_height.

Then, add the height to your row height and declare it. The declaration must be on the viewholder binding, so you have to declare it on your adapter. I'm using `TableRow.LayoutParams` to redeclare the row height.

PS: use `getResources().getDisplayMetrics().density` on declaring the static height, it will detect the dpi of your device.

**Comment by rafivian** [comment]
you can use this to connect the line
 <com.vipul.hp_hp.timelineview.TimelineView
                android:id="@+id/red_marker"
                android:layout_width="wrap_content"
                android:layout_height="match_parent" 
                app:marker_size="35dp"
                app:marker="@drawable/ic_timeline_red"
                app:line_size="2dp"
                app:line="@android:color/black"/>
        </RelativeLayout>


you must use match_parent inside layout_height

**Comment by vipulasri** [comment]
@novanto I got more appropriate solution to your problem. Steps : 

1. Use `FrameLayout` as Parent View.
2. Move `TimeLineView` inside a `FrameLayout` with width and height as `match_parent`.
3. Then move all the other view inside a `LinearLayout` or `RelativeLayout`

For Example : 

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <com.vipul.hp_hp.timelineview.TimelineView
        android:id="@+id/time_marker"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:paddingTop="150dp"
        android:paddingBottom="150dp"
        android:paddingLeft="15dp"
        android:paddingRight="15dp"
        app:marker="@drawable/marker_border_current"
        app:marker_size="18dp"
        app:line_size="2dp"
        app:line="@color/colorDivider"/>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/cardView"
        android:background="?android:attr/selectableItemBackground"
        android:foreground="?android:attr/selectableItemBackground"
        android:focusable="true"
        android:clickable="true"
        app:cardBackgroundColor="@android:color/white"
        app:cardCornerRadius="4dp"
        app:cardPreventCornerOverlap="false"
        app:cardUseCompatPadding="true"
        app:cardElevation="4dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:paddingLeft="50dp"
            android:paddingStart="50dp"
            android:paddingRight="20dp"
            android:paddingEnd="20dp"
            android:paddingTop="20dp"
            android:paddingBottom="20dp"
            android:orientation="vertical">

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/item_class_id"
                android:gravity="center"
                tools:text="Class - 4"
                android:textColor="@color/primaryText"
                android:textSize="20sp"/>

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/item_class_time"
                android:layout_marginTop="10dp"
                android:gravity="center"
                tools:text="4th May, 2015 8:00 AM"
                android:textColor="@color/secondaryText"
                android:textSize="18sp"/>

            <Button
                android:layout_width="wrap_content"
                android:layout_height="35dp"
                android:id="@+id/rescheduleButton"
                android:background="@drawable/border_color_primary"
                android:padding="8dp"
                android:text="@string/reschedule"
                android:textColor="@color/colorPrimary"
                android:textSize="12sp"/>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/status_container"
                android:layout_marginTop="30dp"
                android:orientation="vertical">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@string/reschedule_status"
                    android:textColor="@color/primaryText"
                    android:textSize="16sp"/>

                <android.support.v7.widget.AppCompatSeekBar
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="15dp"
                    android:thumb="@drawable/ic_done"
                    android:id="@+id/seekBar"/>

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="10dp"
                    android:orientation="horizontal">

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:layout_gravity="center"
                        android:gravity="start"
                        android:text="@string/applied"
                        android:textColor="@color/primaryText"
                        android:textSize="14sp"/>

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:id="@+id/end_state"
                        android:layout_weight="1"
                        android:gravity="end"
                        android:layout_gravity="center"
                        tools:text="Approved"
                        android:textColor="@color/colorGrey400"
                        android:textSize="14sp"/>

                    </LinearLayout>

            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/comments_container"
                android:layout_marginTop="20dp"
                android:orientation="vertical">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@string/comments"
                    android:textColor="@color/primaryText"
                    android:textSize="14sp"/>

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/item_comments"
                    android:layout_marginTop="5dp"
                    tools:text="4th May, 2015 8:00 AM"
                    android:textColor="@color/secondaryText"
                    android:textSize="12sp"/>

            </LinearLayout>

        </LinearLayout>

    </android.support.v7.widget.CardView>

    </LinearLayout>

</FrameLayout>
```
