### ISSUE TITLE
Marker is invisible when markerInCenter is set to true

### ISSUE THREAD

**Issue by dondell** [vipulasri/Timeline-View#90]
**Describe the bug**
I tried setting markerInCenter = true, but the marker will make it invisible

**To Reproduce**
markerInCenter = true

**Screenshot**
![Screenshot_20200305-171708](https://user-images.githubusercontent.com/4174860/75966513-71fb6f00-5f05-11ea-8f50-d7917b6138bd.png)

**Comment by vipulasri** [comment]
Can you show me what all options you have applied on combination to that?

**Comment by vipulasri** [comment]
@dondell I have fixed the issue in new release i.e 1.1.4
I will update the sample as well.
