### ISSUE TITLE
Public access to TimelineView.LineType 

### ISSUE THREAD

**Issue by DenShlk** [vipulasri/Timeline-View#91]
I use Timeline view in recyclerview, and I want to set linetype in my viewholder like `TimelineView.LineType.NORMAL`
Unfortunately, I have to copy LineType to Adapter class, because it has private access.
I think LineType can be public like  LineOrientation or LineStyle.

**Comment by vipulasri** [comment]
@DenShlk You can add your custom implementation in `getItemViewType()` method in your recyclerview. 

You can also check out the `TimelineView.getTimeLineViewType()` method in the library to get understand the library implementation and then add your custom one.

**Comment by DenShlk** [comment]
Why my ItemTypes should be equal to LineType?

**Comment by vipulasri** [comment]
> Why my ItemTypes should be equal to LineType?

Because on the basis of `LineType` int values, the library knows what to render if its Normal, Start or End line.

**Comment by DenShlk** [comment]
Sorry, about that. I didn't know about getTimeLineViewType.
I see now, thanks for the reply!
