### ISSUE TITLE
Not Change the color of the time line view in Java android

### ISSUE THREAD

**Issue by lahari509** [vipulasri/Timeline-View#93]
Hi, I am using the vipulsari timeline library. I have a list of geolocation places in recycler view.  When I reached a certain place, I need to change the color of that dotted line as green color. But for me it shows a grey color . can you help me out why
the color is not changing.

My XML code is:

<?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="horizontal"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginLeft="10dp"
    android:layout_marginRight="10dp">

    <com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/timeline"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        app:markerSize="20dp"
        app:markerPaddingTop="5dp"
        app:lineWidth="3dp"
        app:startLineColor="#4C4949"
        app:endLineColor="#4C4949"
        app:lineStyle="dash"/>
    
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"

            android:layout_marginTop="15dp"
            android:layout_marginBottom="15dp"
            android:layout_marginStart="10dp"
            android:layout_marginEnd="5dp"
            android:padding="15dp"
            android:orientation="horizontal">

            <androidx.appcompat.widget.AppCompatTextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/text_timeline_date"
                android:layout_gravity="center"
                android:layout_marginEnd="5dp"
                android:paddingStart="5dp"
                android:paddingEnd="5dp"
                android:layout_weight="1"
                android:textSize="14sp"
                android:textStyle="bold"
                tools:text="hyderabad"
                tools:ignore="RtlSymmetry" />

            <Button
                android:id="@+id/arrived"
                android:layout_width="wrap_content"
                android:layout_height="30dp"
                android:layout_gravity="end"
                android:text="arrived"
                android:backgroundTint="#FF8C00"
                android:background="@drawable/buttonbg"
                android:visibility="gone"
                android:textColor="#fff"
                android:textSize="12sp"
                android:textStyle="bold"/>
        </LinearLayout>

</LinearLayout>

And in recycler view adapter class I am changing the color of the timeline view when it reaches a certain point.

     if(distance < 80){

                            Toast.makeText(context,"Reached the destination point"+timeLineModelList.get(i).getLocation(),Toast.LENGTH_SHORT).show();
                            ((ViewHolder) holder).timelineView.setStartLineColor(R.color.green, 0);
                            ((ViewHolder) holder).timelineView.setEndLineColor(R.color.green, 0);
                        }
![WhatsApp Image 2020-07-07 at 1 10 24 PM](https://user-images.githubusercontent.com/26715838/86739577-9bfba400-c053-11ea-8a7b-9a9babb0af57.jpeg)

Plz, help me out as soon as possible.

**Comment by vipulasri** [comment]
@lahari509 can you show me the XML and code you have configured?

**Comment by lahari509** [comment]
@vipulasri  i have added my xml and adapter class where i am changing the color of the line.

**Comment by vipulasri** [comment]
@lahari509 In your adapter you are directly setting color, You need to set the color to start and end line using 
`ContextCompat.getColor(this, R.color.green)`.

**Comment by lahari509** [comment]
@vipulasri where i need to write this code. I am getting the color from values and it is also showing the color.

**Comment by lahari509** [comment]
thanks its working now

**Comment by lahari509** [comment]
@vipulasri  But there is a problem why it is changing the whole timeline view instead of the reached point
![WhatsApp Image 2020-07-07 at 2 11 02 PM](https://user-images.githubusercontent.com/26715838/86750689-c4879c00-c05b-11ea-86e1-11404bc16c13.jpeg)

**Comment by vipulasri** [comment]
That logic you need to handle in your code. Library isn't doing anything.
