### ISSUE TITLE
My card layout doesn't stretch to the parent width 

### ISSUE THREAD

**Issue by Hacchuu** [vipulasri/Timeline-View#94]
My card layout does not stretch to the parent width but it does in the preview of the card item xml. But once each card gets inflated it feels like it's wrap_content but in reality it's match parent. Is there any help?

**Comment by vipulasri** [comment]
@Hacchuu can you please share the XML for the issue.

**Comment by Hacchuu** [comment]
XML of my card Item. 

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_gravity="center_horizontal"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginLeft="10dp"
    android:layout_marginRight="10dp">

    <com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/timeline"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        app:markerSize="20dp"
        app:lineWidth="2dp"
        app:markerInCenter="true"
        app:startLineColor="@color/colorPrimaryDark"
        app:endLineColor="@color/colorPrimaryDark"
        app:linePadding="5dp" />

    <com.google.android.material.card.MaterialCardView
        android:id="@+id/cardID"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="15dp"
        android:layout_marginBottom="15dp"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="5dp"
        app:cardBackgroundColor="@color/colorPrimary"
        app:contentPadding="15dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:gravity="center"
            android:orientation="vertical">

            <androidx.appcompat.widget.AppCompatTextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/timeline_date"
                android:textSize="12sp"
                tools:text="24 JAN" />

            <androidx.appcompat.widget.AppCompatTextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="5dp"
                android:id="@+id/timeline_title"
                android:textColor="@android:color/black"
                tools:text="Order Successfully Completed" />

        </LinearLayout>

    </com.google.android.material.card.MaterialCardView>

</LinearLayout>

Part of the XML in my main activity

<LinearLayout
        android:id="@+id/LinearView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/card">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/detailsRecycler"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layoutAnimation="@anim/layout_animation"
                android:scrollbars="vertical"
                android:paddingLeft="20dp"
                android:paddingRight="10dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="1.0"
                tools:listitem="@layout/details_item">

            </androidx.recyclerview.widget.RecyclerView>
        </androidx.constraintlayout.widget.ConstraintLayout>
    </LinearLayout>

**Comment by vipulasri** [comment]
Please post the full XML, it's missing the root.

**Comment by Hacchuu** [comment]
The item XML is whole except the linear layout
Entire main XML contains a card with many fields and down below is your recycler view. 

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#b3dbc3"
    tools:context="com.story.mipsa.attendancetracker.SubjectDetails">

    <androidx.cardview.widget.CardView
        android:id="@+id/card"
        android:layout_width="match_parent"
        android:layout_height="270dp"
        android:layout_margin="5dp"
        android:layout_marginStart="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginBottom="8dp"
        android:padding="10dp"
        app:cardBackgroundColor="#83ad93"
        app:cardCornerRadius="20dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.016">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">


            <TextView
                android:id="@+id/nameSubjectDets"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Subject Name"
                android:textColor="@color/colorPrimary"
                android:textSize="30sp"
                android:textStyle="bold"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.07" />

            <TextView
                android:id="@+id/T3"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Classes Skipped:"
                android:textColor="	#ffffff"
                android:textSize="20sp"
                android:textStyle="bold"
                tools:ignore="OnClick"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.066"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/T2"
                app:layout_constraintVertical_bias="0.245" />

            <TextView
                android:id="@+id/absentFill"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:hint="20"
                android:textColor="	#ffffff"
                android:textSize="20sp"
                android:textStyle="bold"
                tools:ignore="OnClick"
                app:layout_constraintBaseline_toBaselineOf="@id/T3"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.0"
                app:layout_constraintStart_toEndOf="@+id/T3"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.767" />

            <TextView
                android:id="@+id/T4"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginEnd="16dp"
                android:text="Attendance"
                android:textColor="@color/colorPrimary"
                android:textSize="20sp"
                android:textStyle="bold"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.898"
                app:layout_constraintStart_toEndOf="@+id/T1"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.354" />

            <TextView
                android:id="@+id/T2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Classes Attended: "
                android:textColor="	#ffffff"
                android:textSize="20sp"
                android:textStyle="bold"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.072"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/T1"
                app:layout_constraintVertical_bias="0.153" />

            <TextView
                android:id="@+id/presentFill"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginEnd="136dp"
                android:hint="20"
                android:textColor="@color/colorPrimary"
                android:textSize="20sp"
                android:textStyle="bold"
                app:layout_constraintBaseline_toBaselineOf="@+id/T2"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.0"
                app:layout_constraintStart_toEndOf="@+id/T2"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.55"
                tools:ignore="OnClick" />

            <TextView
                android:id="@+id/T1"
                android:layout_width="wrap_content"

                android:layout_height="wrap_content"
                android:text="Total Classes:"
                android:textColor="	#ffffff"
                android:textSize="20sp"
                android:textStyle="bold"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.069"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.322"
                tools:ignore="OnClick" />

            <TextView
                android:id="@+id/totalFill"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:hint="20"
                android:textColor="@color/colorPrimary"
                android:textSize="20sp"
                android:textStyle="bold"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.0"
                app:layout_constraintStart_toEndOf="@+id/T1"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.322"
                tools:ignore="OnClick" />

            <TextView
                android:id="@+id/outcome"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginBottom="8dp"
                android:background="@drawable/rounded_corner_background_green"
                android:text="Situation"
                android:textColor="@color/colorPrimaryDark"
                android:textSize="20sp"
                android:textStyle="bold"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.952"
                tools:ignore="OnClick" />

            <TextView
                android:id="@+id/percent"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="100%"
                android:textColor="	#ffffff"
                android:textSize="25dp"
                android:textStyle="bold"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.884"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/T4"
                app:layout_constraintVertical_bias="0.123" />

        </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.cardview.widget.CardView>

    <LinearLayout
        android:id="@+id/LinearView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/card">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/detailsRecycler"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layoutAnimation="@anim/layout_animation"
                android:scrollbars="vertical"
                android:paddingLeft="20dp"
                android:paddingRight="10dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="1.0"
                tools:listitem="@layout/details_item">

            </androidx.recyclerview.widget.RecyclerView>
        </androidx.constraintlayout.widget.ConstraintLayout>
    </LinearLayout>

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by vipulasri** [comment]
As far as I can see it's not the issue with the library but with your implementation. Hence, closing the issue.
