### ISSUE TITLE
line does not show through xml

### ISSUE THREAD

**Issue by vipCodeError** [vipulasri/Timeline-View#96]
Line not showing through xml.

`  <LinearLayout
                android:orientation="horizontal"
                android:id="@+id/order_timeline"
                android:weightSum="4"
                android:layout_margin="8dp"
                android:background="@drawable/rounded_card"
                android:layout_below="@id/card_view3"
                android:layout_width="match_parent"
                android:layout_height="100dp">

                <LinearLayout
                    android:layout_gravity="center_vertical"
                    android:layout_weight="1"
                    android:orientation="vertical"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content">

                    <TextView
                        android:text="Order"
                        android:fontFamily="@font/archia"
                        android:letterSpacing="0.1"
                        android:textSize="10sp"
                        android:textAlignment="center"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"/>
                    <com.github.vipulasri.timelineview.TimelineView
                        android:id="@+id/order_pending_timeline"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="16dp"
                        app:markerSize="20dp"
                        app:lineWidth="2dp"
                        app:linePadding="5dp"
                        app:marker="@drawable/marker_green_dot"
                        app:startLineColor="#FFFFFF"
                        app:lineOrientation="horizontal"
                        app:endLineColor="#151414"/>

                </LinearLayout>

                <LinearLayout
                    android:layout_gravity="center_vertical"
                    android:layout_weight="1"
                    android:orientation="vertical"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content">

                    <TextView
                        android:text="Proccessed"
                        android:fontFamily="@font/archia"
                        android:letterSpacing="0.1"
                        android:textSize="10sp"
                        android:textAlignment="center"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"/>
                    <com.github.vipulasri.timelineview.TimelineView
                        android:id="@+id/proccessed_timeline"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="16dp"
                        app:markerSize="20dp"
                        app:lineWidth="2dp"
                        app:marker="@drawable/marker_dot"
                        app:startLineColor="#151414"
                        app:lineOrientation="horizontal"
                        app:endLineColor="#151414"/>

                </LinearLayout>

                <LinearLayout
                    android:layout_gravity="center_vertical"
                    android:layout_weight="1"
                    android:orientation="vertical"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content">

                    <TextView
                        android:text="Out of Delivery"
                        android:fontFamily="@font/archia"
                        android:letterSpacing="0.1"
                        android:textSize="10sp"
                        android:textAlignment="center"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"/>
                    <com.github.vipulasri.timelineview.TimelineView
                        android:id="@+id/out_of_delivery_timeline"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="16dp"
                        app:markerSize="20dp"
                        app:marker="@drawable/marker_dot"
                        app:lineWidth="2dp"
                        app:startLineColor="#151414"
                        app:lineOrientation="horizontal"
                        app:endLineColor="#151414"/>

                </LinearLayout>

                <LinearLayout
                    android:layout_gravity="center_vertical"
                    android:layout_weight="1"
                    android:orientation="vertical"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content">

                    <TextView
                        android:text="Delivered"
                        android:fontFamily="@font/archia"
                        android:letterSpacing="0.1"
                        android:textSize="10sp"
                        android:textAlignment="center"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"/>
                    <com.github.vipulasri.timelineview.TimelineView
                        android:id="@+id/delivered_timeline"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="16dp"
                        app:marker="@drawable/marker_dot"
                        app:markerSize="20dp"
                        app:lineWidth="2dp"
                        app:lineStyle="dash"
                        app:startLineColor="#151414"
                        app:lineOrientation="horizontal"
                        app:endLineColor="#FFFFFF"/>

                </LinearLayout>
`

Screenshot 
https://drive.google.com/file/d/1hQtzaheuEn1ovg2LTOGD_mjtZ2K64KNO/view?usp=sharing

**Comment by vipulasri** [comment]
Can you please post the adapter code as well ?

**Comment by vipCodeError** [comment]
> Can you please post the adapter code as well ?

I am not using recycler view adapter . I just added four timeline xml and changes their marker and end line and start line color .

**Comment by vipulasri** [comment]
@vipCodeError This is not how this library works. Please follow the steps mentioned in the readme file.

**Comment by giglopavel** [comment]
@vipulasri  Thanks for this library but I didn't see anything in your readme file. 

I just put it into my xml it shows line in my xml view but when i run this my emulator doesn't show any line. Can you please help... 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_height="match_parent">


    <com.github.vipulasri.timelineview.TimelineView
        android:id="@+id/timeline"
        android:layout_width="wrap_content"
        android:layout_height="@dimen/_100sdp"
        app:markerSize="20dp"
        app:lineWidth="2dp"
        app:startLineColor="@color/black"
        app:endLineColor="@color/black"
        tools:ignore="MissingConstraints"
        android:layout_centerInParent="true"
        app:markerInCenter="true"
        />

</RelativeLayout>

**Comment by vipulasri** [comment]
@giglopavel Readme was recently updated to include the official documentation link, which now provides better implementation documentation. You can access it from here: 
https://github.com/vipulasri/Timeline-View?tab=readme-ov-file#documentation
or 
https://vipulasri.github.io/Timeline-View/

For a recyclerview example: https://vipulasri.github.io/Timeline-View/timelineview/recyclerview/
