### ISSUE TITLE
StartLineColor 和EndLineColor 不起作用 先排除ViewHolder里是否timeline.initLine(viewType);

### ISSUE THREAD

**Issue by cuilingling** [vipulasri/Timeline-View#99]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2XL]
 - OS: [e.g. Android 9.0]
 - Version [e.g. 28]

**Comment by vipulasri** [comment]
@cuilingling Please add more information to your issue, so that I can debug the problem.
